### ISSUE TITLE
Clarification regarding DFT

### ISSUE THREAD

**Issue by Muhammad4hmed** [HSE-LAMBDA/IDAO-2022#1]
Hi, its mentioned that ```DFT is not allowed; and, its use will disqualify the modeling solution from the competition```
Can you please tell me what is it? and why is it not allowed? The megnet library you used in your baseline, is this library in anyway use that?

**Comment by dimka11** [comment]
@Muhammad4hmed probably this is https://en.wikipedia.org/wiki/Density_functional_theory

**Comment by Muhammad4hmed** [comment]
> @Muhammad4hmed probably this is https://en.wikipedia.org/wiki/Density_functional_theory

Yes I did read it but my question is ```The megnet library you used in your baseline, is this library in anyway use that?```

**Comment by analokmaus** [comment]
DFT is forbidden because it is how the target values are calculated, like many other similar competitions. And of course, it is never used in the baseline solution.
